config:
  backup: true
  create: true
  dotpath: dotfiles
dotfiles:
  d_colours:
    dst: ~/.config/urxvt/colours
    src: config/urxvt/colours
  d_fonts:
    dst: ~/.config/urxvt/fonts
    src: config/urxvt/fonts
  d_i3:
    dst: ~/.i3
    src: i3
  d_skins:
    dst: ~/.local/share/mc/skins
    src: local/share/mc/skins
  f_bash_aliases:
    dst: ~/.bash_aliases
    src: bash_aliases
  f_bash_logout:
    dst: ~/.bash_logout
    src: bash_logout
  f_bashrc:
    dst: ~/.bashrc
    src: bashrc
  f_compton.conf:
    dst: ~/.compton.conf
    src: compton.conf
  f_dunstrc:
    dst: ~/.config/dunst/dunstrc
    src: config/dunst/dunstrc
  f_edit:
    dst: ~/.bin/edit
    src: bin/edit
  f_feh_brow.sh:
    dst: ~/.bin/feh_brow.sh
    src: bin/feh_brow.sh
  f_gitconfig:
    dst: ~/.gitconfig
    src: gitconfig
  f_htoprc:
    dst: ~/.config/htop/htoprc
    src: config/htop/htoprc
  f_ini:
    dst: ~/.config/mc/ini
    src: config/mc/ini
  f_inputrc:
    dst: ~/.inputrc
    src: inputrc
  f_keyset:
    dst: ~/.config/urxvt/KeySet
    src: config/urxvt/KeySet
  f_mc.ext:
    dst: ~/.config/mc/mc.ext
    src: config/mc/mc.ext
  f_pa_vol:
    dst: ~/.bin/pa_vol
    src: bin/pa_vol
  f_panels.ini:
    dst: ~/.config/mc/panels.ini
    src: config/mc/panels.ini
  f_profile:
    dst: ~/.profile
    src: profile
  f_xinitrc:
    dst: ~/.xinitrc
    src: xinitrc
  f_xresources:
    dst: ~/.Xresources
    src: Xresources
profiles:
  Yura-Acer:
  - f_xinitrc
  - f_profile
  - f_inputrc
  - f_gitconfig
  - f_compton.conf
  - f_bashrc
  - f_bash_logout
  - f_bash_aliases
  - f_xresources
  - f_edit
  - f_feh_brow.sh
  - f_pa_vol
  - f_dunstrc
  - f_htoprc
  - f_ini
  - f_mc.ext
  - f_panels.ini
  - d_colours
  - d_fonts
  - f_keyset
  - d_i3
  - d_skins
