#!/usr/bin/perl
#
# Copyright 2014 Pierre Mavro <deimos@deimos.fr>
# Copyright 2014 Vivien Didelot <vivien@didelot.org>
#
# Licensed under the terms of the GNU GPL v3, or any later version.
#
# This script is meant to use with i3blocks. It parses the output of the "acpi"
# command (often provided by a package of the same name) to read the status of
# the battery, and eventually its remaining time (to full charge or discharge).
#
# The color will gradually change for a percentage below 85%, and the urgency
# (exit code 33) is set if there is less that 5% remaining.
#
# Modified by Raphael. Ribeiro <raphaelpr01@gmail.com>

use strict;
use warnings;
use utf8;

my $battery_name = $ENV{'battery_name'};
my $battery_number = $ENV{'battery_number'};

# read the first line of the "acpi" command output
open (ACPI, "/gnu/store/l20khwgf1n4fjd8i26bw16zhjc9ffhn7-acpi-1.7/bin/acpi -b | grep 'Battery $battery_number' |") or die "Can't exec acpi: $!\n";
my $acpi = <ACPI>;
close(ACPI);

# fail on unexpected output
if ($acpi !~ /: (Not charging|Discharging|Full|Unknown|Charging|Full), (\d+)%/) {
    exit 0;
    # die "$acpi\n";
}
my $status = $1;
my $percent = $2;
my $full_text = "$percent%";

if ($status eq 'Discharging' || $status eq 'Unknown' || $status eq 'Not charging') {
    if ($percent < 10) {
        $full_text = ' ' . $full_text ;
    } elsif ($percent < 25) {
        $full_text = ' ' . $full_text ;
    } elsif ($percent < 50) {
        $full_text = ' ' . $full_text ;
    } elsif ($percent < 75) {
        $full_text = ' ' . $full_text ;
    } elsif ($percent <= 100) {
        $full_text = ' ' . $full_text ;
    }
} elsif ($status eq 'Charging') {
    $full_text = ' ' . $full_text ;
} elsif ($status eq 'Full') {
    $full_text = ' ' . $full_text ;
} else {
    die "$status";
}

# print text
print "$battery_name $full_text\n";
print "$battery_name $full_text\n";

# consider color only on discharge
if ($status ne 'Charging' && $status ne 'Full') {
    if ($percent < 10) {
        print "#FF0000\n";
    } elsif ($percent < 40) {
        print "#FFAE00\n";
    } elsif ($percent < 60) {
        # print "#FFF600\n";
    } elsif ($percent <= 100) {
        # print "#A8FF00\n";
    }
}

# urgent if less then 10 and discharging
if ($percent < 10 && $status eq 'Discharging') {
    exit(33);
} else {
    exit(0);
}
