#!/usr/bin/perl

use strict;
use warnings;
use utf8;

my $xbin_table = "⠀⠁⠊⠋⠂⠃⠜⠝⠔⠕⠞⠟⠖⠗⠌⠍⠄⠅⠎⠏⠆⠇⡸⡹⡰⡱⡺⡻⡲⡳⡨⡩⡠⡡⡪⡫⡢⡣⡼⡽⡴⡵⡾⡿⡶⡷⡬⡭⡤⡥⡮⡯⡦⡧⡘⡙⡐⡑⡚⡛⡒⡓⡈⡉⡀⡁⡊⡋⡂⡃⡜⡝⡔⡕⡞⡟⡖⡗⡌⡍⡄⡅⡎⡏⡆⡇⢸⢹⢰⢱⢺⢻⢲⢳⢨⢩⢠⢡⢪⢫⢢⢣⢼⢽⢴⢵⢾⢿⢶⢷⢬⢭⢤⢥⢮⢯⢦⢧⢘⢙⢐⢑⢚⢛⢒⢓⢈⢉⢀⢁⢊⢋⢂⢃⢜⢝⢔⢕⢞⢟⢖⢗⢌⢍⢄⢅⢎⢏⢆⢇⣸⣹⣰⣱⣺⣻⣲⣳⣨⣩⣠⣡⣪⣫⣢⣣⣼⣽⣴⣵⣾⣿⣶⣷⣬⣭⣤⣥⣮⣯⣦⣧⣘⣙⣐⣑⣚⣛⣒⣓⣈⣉⣀⣁⣊⣋⣂⣃⣜⣝⣔⣕⣞⣟⣖⣗⣌⣍⣄⣅⣎⣏⣆⣇⠸⠹⠰⠱⠺⠻⠲⠳⠨⠩⠠⠡⠪⠫⠢⠣⠼⠽⠴⠵⠾⠿⠶⠷⠬⠭⠤⠥⠮⠯⠦⠧⠘⠙⠐⠑⠚⠛⠒⠓⠈⠉";

sub to_xbin {
    my ($number) = @_;
    my $result = "";
    while ($number > 0) {
        my $idx = $number & 255;
        $result = join "", substr($xbin_table, $idx, 1), $result;
        $number = $number >> 8;
        if ($idx > 85) {
            $number = $number + 1;
        }
    }
    return $result;
}

my ($sec,$min,$hour,$mday,$mon,$year,$wday,$yday,$isdst) = localtime();

# $mday = to_xbin($mday);
# $mon = to_xbin($mon + 1);
# $year = to_xbin($year);

print "│$mday│$mon│日年$year│\n";
print "│$mday│$mon│日年$year│\n";

# my $acpi;
# my $status;
# my $percent;
# my $full_text;
# my $short_text;

# # read the first line of the "acpi" command output
# open (ACPI, 'acpi -b |') or die "Can't exec acpi: $!\n";
# $acpi = <ACPI>;
# close(ACPI);
# # fail on unexpected output
# if ($acpi !~ /: (\w+), (\d+)%/) {
#     die "$acpi\n";
# }
# $status = $1;
# $percent = $2;
# $full_text = "$percent%";
# if ($status eq 'Discharging') {
#     if ($percent < 10) {
#         $full_text = '  ' . $full_text ;
#     } elsif ($percent < 25) {
#         $full_text = '  ' . $full_text ;
#     } elsif ($percent < 50) {
#         $full_text = '  ' . $full_text ;
#     } elsif ($percent < 75) {
#         $full_text = '  ' . $full_text ;
#     } elsif ($percent <= 100) {
#         $full_text = '  ' . $full_text ;
#     }
# } elsif ($status eq 'Charging') {
#     $full_text = '  ' . $full_text ;
# } elsif ($status eq 'Full') {
#     $full_text = '  ' . $full_text ;
# }
# $short_text = $full_text;
# #if ($acpi =~ /(\d\d:\d\d):/) {
# #    $full_text .= " ($1)";
# #}
# # print text
# print "$full_text\n";
# print "$short_text\n";
# # consider color and urgent flag only on discharge
# if ($status eq 'Discharging') {
#     if ($percent < 10) {
#         print "#FF0000\n";
#     } elsif ($percent < 40) {
#         print "#FFAE00\n";
#     } elsif ($percent < 60) {
#         # print "#FFF600\n";
#     } elsif ($percent <= 100) {
#         # print "#A8FF00\n";
#     }
#     if ($percent < 5) {
#         exit(33);
#     }
# }
exit(0);
