#!/usr/bin/perl
#
# Copyright 2014 Pierre Mavro <deimos@deimos.fr>
# Copyright 2014 Vivien Didelot <vivien@didelot.org>
#
# Licensed under the terms of the GNU GPL v3, or any later version.
#
# This script is meant to use with i3blocks. It parses the output of the "acpi"
# command (often provided by a package of the same name) to read the status of
# the battery, and eventually its remaining time (to full charge or discharge).
#
# The color will gradually change for a percentage below 85%, and the urgency
# (exit code 33) is set if there is less that 5% remaining.
#
# Modified by Raphael. Ribeiro <raphaelpr01@gmail.com>
use strict;
use warnings;
use utf8;
my $status;
my $percent;
my $full_text;
my $short_text;
my $which;
##my $bat_number = $ENV{BLOCK_INSTANCE} || 0;
my $bat_ext = 1;
my $bat_int = 0;

# read the first line of the "acpi" command output
open (I_ACPI, "acpi -b | grep 'Battery $bat_int' |") or die "Can't exec acpi: $!\n";
my $int_acpi = <I_ACPI>;
close(I_ACPI);
# fail on unexpected output
if ($int_acpi !~ /: (\w+), (\d+)%/) {
    exit 0;
    #die "$int_acpi\n";
}
my $int_status = $1;
my $int_percent = $2;
my $int_full_text = "$int_percent%";

# read the first line of the "acpi" command output
open (E_ACPI, "acpi -b | grep 'Battery $bat_ext' |") or die "Can't exec acpi: $!\n";
my $ext_acpi = <E_ACPI>;
close(E_ACPI);
# fail on unexpected output
if ($ext_acpi !~ /: (\w+), (\d+)%/) {
    exit 0;
    # die "$ext_acpi\n";
}
my $ext_status = $1;
my $ext_percent = $2;
my $ext_full_text = "$ext_percent%";

if ($int_status eq 'Charging' || $int_status eq 'Discharging') {
    $status = $int_status;
    $percent = $int_percent;
    $full_text = 'I ' . $int_full_text;
} else {
    $status = $ext_status;
    $percent = $ext_percent;
    $full_text = 'E ' . $ext_full_text;
}

if ($status eq 'Discharging') {
    if ($percent < 10) {
        $full_text = '  ' . $full_text ;
    } elsif ($percent < 25) {
        $full_text = '  ' . $full_text ;
    } elsif ($percent < 50) {
        $full_text = '  ' . $full_text ;
    } elsif ($percent < 75) {
        $full_text = '  ' . $full_text ;
    } elsif ($percent <= 100) {
        $full_text = '  ' . $full_text ;
    }
} elsif ($status eq 'Charging') {
    $full_text = '  ' . $full_text ;
} elsif ($status eq 'Full' || $status eq 'Unknown') {
    $full_text = '  ' . $full_text ;
}
$short_text = $full_text;
#if ($acpi =~ /(\d\d:\d\d):/) {
#    $full_text .= " ($1)";
#}
# print text
print "$full_text\n";
print "$short_text\n";
# consider color and urgent flag only on discharge
if ($status eq 'Discharging') {
    if ($percent < 10) {
        print "#FF0000\n";
    } elsif ($percent < 40) {
        print "#FFAE00\n";
    } elsif ($percent < 60) {
        # print "#FFF600\n";
    } elsif ($percent <= 100) {
        # print "#A8FF00\n";
    }
    if ($percent < 5) {
        exit(33);
    }
}
exit(0);
