(define-module (rsauex services pam-u2f)
  #:use-module ((guix))
  #:use-module ((gnu))
  #:export (pam-u2f-entry))

(define* (pam-u2f-entry control #:rest args)
  (pam-entry (control control)
             (module (file-append (@ (gnu packages security-token) pam-u2f)
                                  "/lib/security/pam_u2f.so"))
             (arguments args)))
